package com.kvteam.deliverytracker.core.common

const val NetworkError = "NetworkError"
const val InvalidResponseBody = "InvalidResponseBody"
const val Unauthorized = "Unauthorized"

const val ServerError = "ServerError"
const val InvalidInputParameter = "InvalidQueryParameter"
const val UserNotFound = "UserNotFound"
const val UserWithoutRole = "UserWithoutRole"
const val UserNotInRole = "UserNotInRole"
const val IdentityError = "IdentityError"
const val InvitationDoesnotExist = "InvitationDoesnotExist"
const val InvitationExpired = "InvitationExpired"
const val InstanceAlreadyHasCreator = "InstanceAlreadyHasCreator"
const val PerformerInAnotherInstance = "PerformerInAnotherInstance"
const val TaskNotFound = "TaskNotFound"
const val IncorrectTaskState = "IncorrectTaskState"
const val IncorrectTaskStateTransition = "IncorrectTaskStateTransition"
const val TaskIsForbidden = "TaskIsForbidden"